/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ContainerNavigation {
        "ctaText"?: string;
    }
    interface ProductNavigation {
        /**
          * Product logo
         */
        "productLogo": string;
        /**
          * Descriptor that allow to load links to different page
         */
        "quickLinks": string;
    }
}
declare global {
    interface HTMLContainerNavigationElement extends Components.ContainerNavigation, HTMLStencilElement {
    }
    var HTMLContainerNavigationElement: {
        prototype: HTMLContainerNavigationElement;
        new (): HTMLContainerNavigationElement;
    };
    interface HTMLProductNavigationElement extends Components.ProductNavigation, HTMLStencilElement {
    }
    var HTMLProductNavigationElement: {
        prototype: HTMLProductNavigationElement;
        new (): HTMLProductNavigationElement;
    };
    interface HTMLElementTagNameMap {
        "container-navigation": HTMLContainerNavigationElement;
        "product-navigation": HTMLProductNavigationElement;
    }
}
declare namespace LocalJSX {
    interface ContainerNavigation {
        "ctaText"?: string;
    }
    interface ProductNavigation {
        /**
          * Product logo
         */
        "productLogo"?: string;
        /**
          * Descriptor that allow to load links to different page
         */
        "quickLinks"?: string;
    }
    interface IntrinsicElements {
        "container-navigation": ContainerNavigation;
        "product-navigation": ProductNavigation;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "container-navigation": LocalJSX.ContainerNavigation & JSXBase.HTMLAttributes<HTMLContainerNavigationElement>;
            "product-navigation": LocalJSX.ProductNavigation & JSXBase.HTMLAttributes<HTMLProductNavigationElement>;
        }
    }
}
